---
title: "Gresham Lab Floww Cytometry Single Timepoint Analysis"
author: 'G. Avecilla, N. Brandt, S. Lauer, F. Abdul-Rahman, D. Gresham'
date: '`r Sys.Date()`'
output: html_notebook
---

This notebook contains the code necessary to analysis flow cytometry data in the Gresham Lab. 

To analyze flow cytometry data, you MUST use the latest version of this code, available on the [Gresham Lab github](https://github.com/GreshamLab/flow).

**Experimental overview**

Write a detailed description of your experiment here including the goal of the analysis and your interpretation of the results.   
If you still see this text it means that you have not described the experiment and whatever follows is meaningless.

*This code is designed for use with the Accuri flow cytometer, which is equiped with the following lasers and filters*

* Blue laser (488 nm)
* FL1 filter = 514/20nm   GFP
* FL3 filter = 575/25nm   YFP

* Yellow/green laser (552 nm)
* FL2 filter = 610/20nm   mCherry, dtomato
* FL4 filter = 586/15nm   DsRed
  
**Requirements**

In order to run this code you need:

* to predefine your gates using the gating.R script
* the gates.Rdata workspace, which contains the gates to be used in this script
* a tab delimited sample sheet in with the first XXXX columns set up as in the example below
* user defined variables, see below and chunk 1

**Output**  
This script generates quality control plots in the notebook and a file(s) with a summary of results.
The user can generate the output file(s) in three different styles: 

1. As a dataframe converted from fcs with all or some of the data.
2. As a dataframe with summary statistics (e.g. median FL1 per sample)
3. As a new .fcs file with additional information (e.g. phenotype or sample information) appended
  
**Variables**
Variables for the user to set can be found in chunk one. These include both required variables (e.g., working directory), and optional variables (e.g., style of ouput). There are some defaults for these variables.

```{r User Defined Variables}
#working directory
dir = '.'
#style of output




```

